displayName=Cox Storage Viewer
author=YamzTheKid
description=View your Chambers of Xeric private storage contents from anywhere in the raid
tags=raids,cox,chambers,xeric,storage,supplies
plugins=com.coxbankviewer.CoxBankPlugin
support=https://github.com/YamzTheKid/cox-bank-viewer